export const CORRECT = [
  {
    children: [
      {
        children: [
          {
            children: [],
            image: 'Proszki',
            showOnHome: false,
            id: 9292,
            name: 'Proszki',
            order: 9292,
          },
          {
            children: [],
            image: 'Płyny i żele',
            showOnHome: false,
            id: 9293,
            name: 'Płyny i żele',
            order: 9293,
          },
          {
            children: [],
            image: 'Kapsułki i tabletki',
            showOnHome: false,
            id: 9294,
            name: 'Kapsułki i tabletki',
            order: 9294,
          },
          {
            children: [],
            image: 'Płyny do płukania',
            showOnHome: false,
            id: 9295,
            name: 'Płyny do płukania',
            order: 9295,
          },
          {
            children: [],
            image: '',
            showOnHome: false,
            id: 9296,
            name: 'Odplamiacze i wybielacze',
            order: 9296,
          },
          {
            children: [],
            image: 'Dodatki do prania',
            showOnHome: false,
            id: 9297,
            name: 'Dodatki do prania',
            order: 9297,
          },
          {
            children: [],
            image: 'Dodatki do suszenia',
            showOnHome: false,
            id: 9298,
            name: 'Dodatki do suszenia',
            order: 9298,
          },
          {
            children: [],
            image: 'Środki do prasowania',
            showOnHome: false,
            id: 9299,
            name: 'Środki do prasowania',
            order: 9299,
          },
          {
            children: [],
            image: 'Akcesoria do prania i prasowania',
            showOnHome: false,
            id: 9313,
            name: 'Akcesoria do prania i prasowania',
            order: 9313,
          },
          {
            children: [],
            image: 'Środki do czyszczenia pralki',
            showOnHome: false,
            id: 9665,
            name: 'Środki do czyszczenia pralki',
            order: 9665,
          },
        ],
        image: 'https://anotherprovider.com/categories/pranie-i-prasowanie.jpg',
        showOnHome: false,
        id: 9288,
        name: 'Pranie i prasowanie',
        order: 1,
      },
      {
        children: [
          {
            children: [],
            image: 'Kapsułki i tabletki do zmywarki',
            showOnHome: false,
            id: 9314,
            name: 'Kapsułki i tabletki do zmywarki',
            order: 9314,
          },
          {
            children: [],
            image: 'Żele i proszki',
            showOnHome: false,
            id: 9315,
            name: 'Żele i proszki',
            order: 9315,
          },
          {
            children: [],
            image: 'Sole do zmywarki',
            showOnHome: false,
            id: 9316,
            name: 'Sole do zmywarki',
            order: 9316,
          },
          {
            children: [],
            image: 'Nabłyszczacze i czyściki',
            showOnHome: false,
            id: 9317,
            name: 'Nabłyszczacze i czyściki',
            order: 9317,
          },
          {
            children: [],
            image: 'Zapachy do zmywarki',
            showOnHome: false,
            id: 9318,
            name: 'Zapachy do zmywarki',
            order: 9318,
          },
          {
            children: [],
            image: 'Płyny do naczyń',
            showOnHome: false,
            id: 9319,
            name: 'Płyny do naczyń',
            order: 9319,
          },
          {
            children: [],
            image: '',
            showOnHome: false,
            id: 9320,
            name: 'Zestawy chemii do zmywania',
            order: 9320,
          },
          {
            children: [],
            image: 'Akcesoria do zmywania',
            showOnHome: false,
            id: 9321,
            name: 'Akcesoria do zmywania',
            order: 9321,
          },
        ],
        image: 'https://anotherprovider.com/categories/zmywanie-naczyn.jpg',
        showOnHome: false,
        id: 9290,
        name: 'Zmywanie naczyń',
        order: 2,
      },
      {
        children: [
          {
            children: [],
            image: 'Środki do czyszczenia kuchni',
            showOnHome: false,
            id: 9303,
            name: 'Środki do czyszczenia kuchni',
            order: 1,
          },
          {
            children: [],
            image: 'Środki do czyszczenia łazienek',
            showOnHome: false,
            id: 9283,
            name: 'Środki do czyszczenia łazienek',
            order: 2,
          },
          {
            children: [],
            image: 'Środki uniwersalne',
            showOnHome: false,
            id: 9301,
            name: 'Środki uniwersalne',
            order: 3,
          },
          {
            children: [],
            image: 'Chusteczki czyszczące',
            showOnHome: false,
            id: 9309,
            name: 'Chusteczki czyszczące',
            order: 4,
          },
          {
            children: [],
            image: 'Do szyb i luster',
            showOnHome: false,
            id: 9282,
            name: 'Do szyb i luster',
            order: 5,
          },
          {
            children: [],
            image: 'Środki do pielęgnacji mebli',
            showOnHome: false,
            id: 9287,
            name: 'Środki do pielęgnacji mebli',
            order: 9287,
          },
          {
            children: [],
            image: 'Do mycia podłóg',
            showOnHome: false,
            id: 9302,
            name: 'Do mycia podłóg',
            order: 9302,
          },
          {
            children: [],
            image: 'Odkamieniacze',
            showOnHome: false,
            id: 9304,
            name: 'Odkamieniacze',
            order: 9304,
          },
          {
            children: [],
            image: 'Środki do toalet i udrażniacze',
            showOnHome: false,
            id: 9305,
            name: 'Środki do toalet i udrażniacze',
            order: 9305,
          },
          {
            children: [],
            image: 'Zawieszki toaletowe',
            showOnHome: false,
            id: 9307,
            name: 'Zawieszki toaletowe',
            order: 9307,
          },
          {
            children: [],
            image: 'Inne preparaty',
            showOnHome: false,
            id: 9310,
            name: 'Inne preparaty',

            order: 9310,
          },
          {
            children: [],
            image: 'Zestawy chemii do sprzątania',
            showOnHome: false,
            id: 9311,
            name: 'Zestawy chemii do sprzątania',
            order: 9311,
          },
          {
            children: [],
            image: 'Akcesoria do sprzątania',
            showOnHome: false,
            id: 9312,
            name: 'Akcesoria do sprzątania',
            order: 9312,
          },
          {
            children: [],
            image: 'Preparaty na insekty',
            showOnHome: false,
            id: 9801,
            name: 'Preparaty na insekty',
            order: 9801,
          },
        ],
        image:
          'https://anotherprovider.com/categories/sprzatanie-i-czyszczenie.jpg',
        showOnHome: false,
        id: 9289,
        name: 'Sprzątanie i czyszczenie',
        order: 3,
      },
      {
        children: [
          {
            children: [],
            image: 'Aerozole i spraye',
            showOnHome: false,
            id: 9322,
            name: 'Aerozole i spraye',
            order: 1,
          },
          {
            children: [],
            image: 'Świece',
            showOnHome: false,
            id: 9327,
            name: 'Świece',
            order: 2,
          },
          {
            children: [],
            image: 'Patyczki',
            showOnHome: false,
            id: 9323,
            name: 'Patyczki',
            order: 3,
          },
          {
            children: [],
            image: 'Inne odświeżacze',
            showOnHome: false,
            id: 9328,
            name: 'Inne odświeżacze',
            order: 9,
          },
          {
            children: [],
            image: 'Dyfuzory',
            showOnHome: false,
            id: 9324,
            name: 'Dyfuzory',
            order: 9324,
          },
          {
            children: [],
            image: 'Żelowe',
            showOnHome: false,
            id: 9325,
            name: 'Żelowe',
            order: 9325,
          },
          {
            children: [],
            image: 'Saszetki',
            showOnHome: false,
            id: 9326,
            name: 'Saszetki',
            order: 9326,
          },
          {
            children: [],
            image: 'Olejki eteryczne',
            showOnHome: false,
            id: 9732,
            name: 'Olejki eteryczne',
            order: 9732,
          },
          {
            children: [],
            image: 'Tealighty i świece bezzapachowe',
            showOnHome: false,
            id: 9800,
            name: 'Tealighty i świece bezzapachowe',
            order: 9800,
          },
          {
            children: [],
            image: 'Woski zapachowe',
            showOnHome: false,
            id: 9804,
            name: 'Woski zapachowe',
            order: 9804,
          },
        ],
        image: 'https://anotherprovider.com/categories/powiew-swiezosci.jpg',
        showOnHome: false,
        id: 9291,
        name: 'Powiew świeżości',
        order: 4,
      },
    ],
    image: 'https://anotherprovider.com/categories/porzadki.jpg',
    showOnHome: true,
    id: 1,
    name: 'Porządki',
    order: 2,
  },
];
