export const INCORRECT = [
  {
    id: 1,
    image: 'https://anotherprovider.com/categories/porzadki.jpg',
    name: 'Porządki',
    order: 2,
    children: [
      {
        id: 9288,
        image: 'https://anotherprovider.com/categories/pranie-i-prasowanie.jpg',
        name: 'Pranie i prasowanie',
        order: 2,
        children: [
          {
            id: 9292,
            image: 'Proszki',
            name: 'Proszki',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9293,
            image: 'Płyny i żele',
            name: 'Płyny i żele',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9294,
            image: 'Kapsułki i tabletki',
            name: 'Kapsułki i tabletki',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9295,
            image: 'Płyny do płukania',
            name: 'Płyny do płukania',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9296,
            image: '',
            name: 'Odplamiacze i wybielacze',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9297,
            image: 'Dodatki do prania',
            name: 'Dodatki do prania',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9298,
            image: 'Dodatki do suszenia',
            name: 'Dodatki do suszenia',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9299,
            image: 'Środki do prasowania',
            name: 'Środki do prasowania',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9313,
            image: 'Akcesoria do prania i prasowania',
            name: 'Akcesoria do prania i prasowania',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9665,
            image: 'Środki do czyszczenia pralki',
            name: 'Środki do czyszczenia pralki',
            order: 2,
            children: [],
            showOnHome: false,
          },
        ],
        showOnHome: false,
      },
      {
        id: 9289,
        image:
          'https://anotherprovider.com/categories/sprzatanie-i-czyszczenie.jpg',
        name: 'Sprzątanie i czyszczenie',
        order: 2,
        children: [
          {
            id: 9282,
            image: 'Do szyb i luster',
            name: 'Do szyb i luster',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9283,
            image: 'Środki do czyszczenia łazienek',
            name: 'Środki do czyszczenia łazienek',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9287,
            image: 'Środki do pielęgnacji mebli',
            name: 'Środki do pielęgnacji mebli',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9301,
            image: 'Środki uniwersalne',
            name: 'Środki uniwersalne',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9302,
            image: 'Do mycia podłóg',
            name: 'Do mycia podłóg',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9303,
            image: 'Środki do czyszczenia kuchni',
            name: 'Środki do czyszczenia kuchni',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9304,
            image: 'Odkamieniacze',
            name: 'Odkamieniacze',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9305,
            image: 'Środki do toalet i udrażniacze',
            name: 'Środki do toalet i udrażniacze',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9307,
            image: 'Zawieszki toaletowe',
            name: 'Zawieszki toaletowe',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9309,
            image: 'Chusteczki czyszczące',
            name: 'Chusteczki czyszczące',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9310,
            image: 'Inne preparaty',
            name: 'Inne preparaty',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9311,
            image: 'Zestawy chemii do sprzątania',
            name: 'Zestawy chemii do sprzątania',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9312,
            image: 'Akcesoria do sprzątania',
            name: 'Akcesoria do sprzątania',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9801,
            image: 'Preparaty na insekty',
            name: 'Preparaty na insekty',
            order: 2,
            children: [],
            showOnHome: false,
          },
        ],
        showOnHome: false,
      },
      {
        id: 9290,
        image: 'https://anotherprovider.com/categories/zmywanie-naczyn.jpg',
        name: 'Zmywanie naczyń',
        order: 2,
        children: [
          {
            id: 9314,
            image: 'Kapsułki i tabletki do zmywarki',
            name: 'Kapsułki i tabletki do zmywarki',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9315,
            image: 'Żele i proszki',
            name: 'Żele i proszki',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9316,
            image: 'Sole do zmywarki',
            name: 'Sole do zmywarki',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9317,
            image: 'Nabłyszczacze i czyściki',
            name: 'Nabłyszczacze i czyściki',

            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9318,
            image: 'Zapachy do zmywarki',
            name: 'Zapachy do zmywarki',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9319,
            image: 'Płyny do naczyń',
            name: 'Płyny do naczyń',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9320,
            image: '',
            name: 'Zestawy chemii do zmywania',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9321,
            image: 'Akcesoria do zmywania',
            name: 'Akcesoria do zmywania',
            order: 2,
            children: [],
            showOnHome: false,
          },
        ],
        showOnHome: false,
      },
      {
        id: 9291,
        image: 'https://anotherprovider.com/categories/powiew-swiezosci.jpg',
        name: 'Powiew świeżości',
        order: 2,
        children: [
          {
            id: 9322,
            image: 'Aerozole i spraye',
            name: 'Aerozole i spraye',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9323,
            image: 'Patyczki',
            name: 'Patyczki',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9324,
            image: 'Dyfuzory',
            name: 'Dyfuzory',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9325,
            image: 'Żelowe',
            name: 'Żelowe',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9326,
            image: 'Saszetki',
            name: 'Saszetki',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9327,
            image: 'Świece',
            name: 'Świece',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9328,
            image: 'Inne odświeżacze',
            name: 'Inne odświeżacze',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9732,
            image: 'Olejki eteryczne',
            name: 'Olejki eteryczne',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9800,
            image: 'Tealighty i świece bezzapachowe',
            name: 'Tealighty i świece bezzapachowe',
            order: 2,
            children: [],
            showOnHome: false,
          },
          {
            id: 9804,
            image: 'Woski zapachowe',
            name: 'Woski zapachowe',
            order: 2,
            children: [],
            showOnHome: false,
          },
        ],
        showOnHome: false,
      },
    ],
    showOnHome: true,
  },
];
