export const INPUT = [
  {
    id: 1,
    name: 'Porządki',
    hasChildren: true,
    url: 'https://exampledataprovider.com/porządki',
    children: [
      {
        id: 9288,
        name: 'Pranie i prasowanie',
        hasChildren: true,
        url: 'https://exampledataprovider.com/porządki/pranie-i-prasowanie',
        children: [
          {
            id: 9292,
            name: 'Proszki',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/pranie-i-prasowanie/proszki',
            children: [],
            Title: 'Proszki',
            MetaTagDescription: 'Proszki',
          },
          {
            id: 9293,
            name: 'Płyny i żele',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/pranie-i-prasowanie/płyny-i-żele',
            children: [],
            Title: 'Płyny i żele',
            MetaTagDescription: 'Płyny i żele',
          },
          {
            id: 9294,
            name: 'Kapsułki i tabletki',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/pranie-i-prasowanie/kapsułki-i-tabletki',
            children: [],
            Title: 'Kapsułki i tabletki',
            MetaTagDescription: 'Kapsułki i tabletki',
          },
          {
            id: 9295,
            name: 'Płyny do płukania',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/pranie-i-prasowanie/płyny-do-płukania',
            children: [],
            Title: 'Płyny do płukania',
            MetaTagDescription: 'Płyny do płukania',
          },
          {
            id: 9296,
            name: 'Odplamiacze i wybielacze',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/pranie-i-prasowanie/odplamiacze-i-wybielacze',
            children: [],
            Title: 'Odplamiacze i wybielacze',
            MetaTagDescription: '',
          },
          {
            id: 9297,
            name: 'Dodatki do prania',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/pranie-i-prasowanie/dodatki-do-prania',
            children: [],
            Title: 'Dodatki do prania',
            MetaTagDescription: 'Dodatki do prania',
          },
          {
            id: 9298,
            name: 'Dodatki do suszenia',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/pranie-i-prasowanie/dodatki-do-suszenia',
            children: [],
            Title: 'Dodatki do suszenia',
            MetaTagDescription: 'Dodatki do suszenia',
          },
          {
            id: 9299,
            name: 'Środki do prasowania',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/pranie-i-prasowanie/środki-do-prasowania',
            children: [],
            Title: 'Środki do prasowania',
            MetaTagDescription: 'Środki do prasowania',
          },
          {
            id: 9313,
            name: 'Akcesoria do prania i prasowania',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/pranie-i-prasowanie/akcesoria-do-prania-i-prasowania',
            children: [],
            Title: 'Akcesoria do prania i prasowania',
            MetaTagDescription: 'Akcesoria do prania i prasowania',
          },
          {
            id: 9665,
            name: 'Środki do czyszczenia pralki',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/pranie-i-prasowanie/środki-do-czyszczenia-pralki',
            children: [],
            Title: 'Środki do czyszczenia pralki',
            MetaTagDescription: 'Środki do czyszczenia pralki',
          },
        ],
        Title: '1',
        MetaTagDescription:
          'https://anotherprovider.com/categories/pranie-i-prasowanie.jpg',
      },
      {
        id: 9289,
        name: 'Sprzątanie i czyszczenie',
        hasChildren: true,
        url: 'https://exampledataprovider.com/porządki/sprzątanie-i-czyszczenie',
        children: [
          {
            id: 9282,
            name: 'Do szyb i luster',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/sprzątanie-i-czyszczenie/do-szyb-i-luster',
            children: [],
            Title: '5',
            MetaTagDescription: 'Do szyb i luster',
          },
          {
            id: 9283,
            name: 'Środki do czyszczenia łazienek',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/sprzątanie-i-czyszczenie/środki-do-czyszczenia-łazienek',
            children: [],
            Title: '2',
            MetaTagDescription: 'Środki do czyszczenia łazienek',
          },
          {
            id: 9287,
            name: 'Środki do pielęgnacji mebli',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/sprzątanie-i-czyszczenie/środki-do-pielęgnacji-mebli',
            children: [],
            Title: 'Środki do pielęgnacji mebli',
            MetaTagDescription: 'Środki do pielęgnacji mebli',
          },
          {
            id: 9301,
            name: 'Środki uniwersalne',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/sprzątanie-i-czyszczenie/środki-uniwersalne',
            children: [],
            Title: '3',
            MetaTagDescription: 'Środki uniwersalne',
          },
          {
            id: 9302,
            name: 'Do mycia podłóg',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/sprzątanie-i-czyszczenie/do-mycia-podłog',
            children: [],
            Title: 'Do mycia podłóg',
            MetaTagDescription: 'Do mycia podłóg',
          },
          {
            id: 9303,
            name: 'Środki do czyszczenia kuchni',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/sprzątanie-i-czyszczenie/środki-do-czyszczenia-kuchni',
            children: [],
            Title: '1',
            MetaTagDescription: 'Środki do czyszczenia kuchni',
          },
          {
            id: 9304,
            name: 'Odkamieniacze',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/sprzątanie-i-czyszczenie/odkamieniacze',
            children: [],
            Title: 'Odkamieniacze',
            MetaTagDescription: 'Odkamieniacze',
          },
          {
            id: 9305,
            name: 'Środki do toalet i udrażniacze',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/sprzątanie-i-czyszczenie/środki-do-toalet-i-udrażniacze',
            children: [],
            Title: 'Środki do toalet i udrażniacze',
            MetaTagDescription: 'Środki do toalet i udrażniacze',
          },
          {
            id: 9307,
            name: 'Zawieszki toaletowe',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/sprzątanie-i-czyszczenie/zawieszki-toaletowe',
            children: [],
            Title: 'Zawieszki toaletowe',
            MetaTagDescription: 'Zawieszki toaletowe',
          },
          {
            id: 9309,
            name: 'Chusteczki czyszczące',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/sprzątanie-i-czyszczenie/chusteczki-czyszczące',
            children: [],
            Title: '4',
            MetaTagDescription: 'Chusteczki czyszczące',
          },
          {
            id: 9310,
            name: 'Inne preparaty',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/sprzątanie-i-czyszczenie/inne-preparaty',
            children: [],
            Title: 'Inne preparaty',
            MetaTagDescription: 'Inne preparaty',
          },
          {
            id: 9311,
            name: 'Zestawy chemii do sprzątania',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/sprzątanie-i-czyszczenie/zestawy-chemii-do-sprzątania',
            children: [],
            Title: 'Zestawy chemii do sprzątania',
            MetaTagDescription: 'Zestawy chemii do sprzątania',
          },
          {
            id: 9312,
            name: 'Akcesoria do sprzątania',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/sprzątanie-i-czyszczenie/akcesoria-do-sprzątania',
            children: [],
            Title: 'Akcesoria do sprzątania',
            MetaTagDescription: 'Akcesoria do sprzątania',
          },
          {
            id: 9801,
            name: 'Preparaty na insekty',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/sprzątanie-i-czyszczenie/preparaty-na-insekty',
            children: [],
            Title: 'Preparaty na insekty',
            MetaTagDescription: 'Preparaty na insekty',
          },
        ],
        Title: '3',
        MetaTagDescription:
          'https://anotherprovider.com/categories/sprzatanie-i-czyszczenie.jpg',
      },
      {
        id: 9290,
        name: 'Zmywanie naczyń',
        hasChildren: true,
        url: 'https://exampledataprovider.com/porządki/zmywanie-naczyń',
        children: [
          {
            id: 9314,
            name: 'Kapsułki i tabletki do zmywarki',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/zmywanie-naczyń/kapsułki-i-tabletki-do-zmywarki',
            children: [],
            Title: 'Kapsułki i tabletki do zmywarki',
            MetaTagDescription: 'Kapsułki i tabletki do zmywarki',
          },
          {
            id: 9315,
            name: 'Żele i proszki',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/zmywanie-naczyń/żele-i-proszki',
            children: [],
            Title: 'Żele i proszki',
            MetaTagDescription: 'Żele i proszki',
          },
          {
            id: 9316,
            name: 'Sole do zmywarki',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/zmywanie-naczyń/sole-do-zmywarki',
            children: [],
            Title: 'Sole do zmywarki',
            MetaTagDescription: 'Sole do zmywarki',
          },
          {
            id: 9317,
            name: 'Nabłyszczacze i czyściki',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/zmywanie-naczyń/nabłyszczacze-i-czyściki',
            children: [],
            Title: 'Nabłyszczacze i czyściki',
            MetaTagDescription: 'Nabłyszczacze i czyściki',
          },
          {
            id: 9318,
            name: 'Zapachy do zmywarki',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/zmywanie-naczyń/zapachy-do-zmywarki',
            children: [],
            Title: 'Zapachy do zmywarki',
            MetaTagDescription: 'Zapachy do zmywarki',
          },
          {
            id: 9319,
            name: 'Płyny do naczyń',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/zmywanie-naczyń/płyny-do-naczyń',
            children: [],
            Title: 'Płyny do naczyń',
            MetaTagDescription: 'Płyny do naczyń',
          },
          {
            id: 9320,
            name: 'Zestawy chemii do zmywania',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/zmywanie-naczyń/zestawy-chemii-do-zmywania',
            children: [],
            Title: 'ZestawyZestawy chemii do zmywania',
            MetaTagDescription: '',
          },
          {
            id: 9321,
            name: 'Akcesoria do zmywania',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/zmywanie-naczyń/akcesoria-do-zmywania',
            children: [],
            Title: 'Akcesoria do zmywania',
            MetaTagDescription: 'Akcesoria do zmywania',
          },
        ],
        Title: '2',
        MetaTagDescription:
          'https://anotherprovider.com/categories/zmywanie-naczyn.jpg',
      },
      {
        id: 9291,
        name: 'Powiew świeżości',
        hasChildren: true,
        url: 'https://exampledataprovider.com/porządki/powiew-świeżości',
        children: [
          {
            id: 9322,
            name: 'Aerozole i spraye',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/powiew-świeżości/aerozole-i-spraye',
            children: [],
            Title: '1',
            MetaTagDescription: 'Aerozole i spraye',
          },
          {
            id: 9323,
            name: 'Patyczki',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/powiew-świeżości/patyczki',
            children: [],
            Title: '3',
            MetaTagDescription: 'Patyczki',
          },
          {
            id: 9324,
            name: 'Dyfuzory',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/powiew-świeżości/dyfuzory',
            children: [],
            Title: 'Dyfuzory',
            MetaTagDescription: 'Dyfuzory',
          },
          {
            id: 9325,
            name: 'Żelowe',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/powiew-świeżości/żelowe',
            children: [],
            Title: 'Żelowe',
            MetaTagDescription: 'Żelowe',
          },
          {
            id: 9326,
            name: 'Saszetki',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/powiew-świeżości/saszetki',
            children: [],
            Title: 'Saszetki',
            MetaTagDescription: 'Saszetki',
          },
          {
            id: 9327,
            name: 'Świece',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/powiew-świeżości/świece',
            children: [],
            Title: '2',
            MetaTagDescription: 'Świece',
          },
          {
            id: 9328,
            name: 'Inne odświeżacze',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/powiew-świeżości/inne-odświeżacze',
            children: [],
            Title: '9',
            MetaTagDescription: 'Inne odświeżacze',
          },
          {
            id: 9732,
            name: 'Olejki eteryczne',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/powiew-świeżości/olejki-eteryczne',
            children: [],
            Title: 'Olejki eteryczne',
            MetaTagDescription: 'Olejki eteryczne',
          },
          {
            id: 9800,
            name: 'Tealighty i świece bezzapachowe',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/powiew-świeżości/tealighty-i-świece-bezzapachowe',
            children: [],
            Title: 'Tealighty i świece bezzapachowe',
            MetaTagDescription: 'Tealighty i świece bezzapachowe',
          },
          {
            id: 9804,
            name: 'Woski zapachowe',
            hasChildren: false,
            url: 'https://exampledataprovider.com/porządki/powiew-świeżości/woski-zapachowe',
            children: [],
            Title: 'Woski zapachowe',
            MetaTagDescription: 'Woski zapachowe',
          },
        ],
        Title: '4',
        MetaTagDescription:
          'https://anotherprovider.com/categories/powiew-swiezosci.jpg',
      },
    ],
    Title: '2#',
    MetaTagDescription: 'https://anotherprovider.com/categories/porzadki.jpg',
  },
];
